server: "hub-cloud.browserstack.com"

common_caps:
  "project": "First Cucumber Android Project"
  "build": "browserstack-build-1"
  "browserstack.debug": true

browser_caps:
  -
    "device": "Google Pixel 3"
    "os_version": "9.0"
    "app": "bs://535003f0b8a8deb290e974b8f2fd32b8bfff0206"
    "name": "first_test"
    "automationName": "Appium"
    "platformName": "Android"
