server: "hub-cloud.browserstack.com"

common_caps:
  "project": "First Cucumber Project"
  "build": "browserstack-build-1"
  "browserstack.debug": true

browser_caps:
  -
    "deviceName": "Google Pixel 3"
    "osVersion": "9.0"
    "app": "bs://535003f0b8a8deb290e974b8f2fd32b8bfff0206"
    "name": "first_test"
    "automationName": "Appium"
    "platformName": "Android"
  -
    "deviceName": "iPhone 13 Pro Max"
    "osVersion": "15"
    "app": "bs://8ecad945acc79dde915b3cf1b1e4809a208916ce"
    "name": "first_test"
    "platformName": "iOS"
